name: ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - scipy
  - numpy
  - click
  - tqdm
  - pandas
  - pytorch-lightning
  - torchsummary
  - pip:
    - ImageHash
    - ninja